// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orqggjascllvypfovibn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ycWdnamFzY2xsdnlwZm92aWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDM4MTQsImV4cCI6MjA2NTIxOTgxNH0.58nxor2OGJwPnvySywDtA2ovzvV-hE-iRIzh0f3uLv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);